### ISSUE TITLE
Comment lancer DoctolibSniper ?

### ISSUE THREAD

**Issue by hista** [alexandredubois/DoctolibSniper#1]
Bonjour,
Désolé pour la question noob :
une fois que le repo est cloné, comment lancer DoctolibSniper ?

**Comment by alexandredubois** [comment]
Bonjour,
1) Si ce n'est pas déjà fait, installer le SDK dotnet core correspondant à votre système depuis ici : https://dotnet.microsoft.com/download
2)Editez le fichier Program.cs avec l'URL correspondant à votre ville (variable doctolibSearchUrl). Si vous souhaitez ignorer les créneaux de certains centres de vaccination, vous pouvez les mentionner dans la variable centersToIgnore.
3) Depuis un terminal ou une invite de commande dans le répertoire cloné, lancez la commande dotnet run et laissez la magie opérer ;)
